#:import FirebaseLoginScreen firebaseloginscreen.firebaseloginscreen.FirebaseLoginScreen

FirebaseLoginScreen:
    size_hint: 1,1
    pos_hint: {"top": 1, "right": 1}
    debug: True
    remember_user: True
    require_email_verification: True
    web_api_key: "AIzaSyCVAZHLsIkT62IyXIQ0p6JMDioZ5-NPVrQ"
    background: "background.jpg"
    on_login_success:
        print("User has logged in. Unique identifier is ", self.localId)

